DROP DATABASE IF EXISTS todo;

CREATE DATABASE todo;

DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS completed;

CREATE TABLE todos(
    id SERIAL PRIMARY KEY NOT NULL,
    task TEXT NOT NULL
);

CREATE TABLE completed (
    id SERIAL PRIMARY KEY NOT NULL,
    task TEXT NOT NULL
);